### ISSUE TITLE
Heh, got ya

### ISSUE THREAD

**Issue by rdebath** [J-Gamer/brainfuck-string-literal#1]
The dot on the line `Clean up used cells.` is supposed to be there, it's part of the program, it prints the newline on the end of the string.

**Comment by SephDB** [comment]
Thanks for letting me know. I tried compiling it as a raw string directly copied from the wiki, but my current TMP algorithm makes the compiler take way too much memory and crashes with an internal segfault. I'm now working on an alternative algorithm.

**Comment by rdebath** [comment]
Humm, this compiles, and runs, for me using `gcc (Debian 6.2.1-5) 6.2.1 20161124` x32 arch.
Still, 1½ Gbyte of RAM is a bit steep.

``` C
#include "brainfuck.h"

template<typename CharT, CharT... C>
constexpr auto operator"" _b()
{
  return bf<C...>{};
}

int main()
{
  "-[++>]++"_b.run();

R"(
Calculate the value 256 and test if it's zero
If the interpreter errors on overflow this is where it'll happen
++++++++[>++++++++<-]>[<++++>-]
+<[>-<
    Not zero so multiply by 256 again to get 65536
    [>++++<-]>[<++++++++>-]<[>++++++++<-]
    +>[>
        # Print "32"
        ++++++++++[>+++++<-]>+.-.[-]<
    <[-]<->] <[>>
        # Print "16"
        +++++++[>+++++++<-]>.+++++.[-]<
<<-]] >[>
    # Print "8"
    ++++++++[>+++++++<-]>.[-]<
<-]<
# Print " bit cells\n"
+++++++++++[>+++>+++++++++>+++++++++>+<<<<-]>-.>-.+++++++.+++++++++++.<.
>>.++.+++++++..<-.>>-
Clean up used cells.
[[-]<]
)"

    ""_b .run();
}
```

**Comment by SephDB** [comment]
Same code, on gcc 5.2.1 on Windows takes >4.5GB of RAM before crashing

**Comment by rdebath** [comment]
That must be x64, ok I tried ... `g++-5 (Debian 5.4.1-3) 5.4.1 20161019` on x64, yup, that gets it upto 4GB the downgrade to v5 increased the memory to about 2GB and the switch to 64bit doubled it after that. I suppose that means there's another half gig of overhead for windows.

Didn't segfault though, even though that VM only had 4GB of ram.

**Comment by SephDB** [comment]
I finished an alternate implementation(see the new branch), but it seems that on my machine it still keeps the same behaviour.

**Comment by rdebath** [comment]
Works the same here too, v6 is about 3G v5 about 4G on x64.

I really don't think much of C++ templates, when two different implementations by a competent programmer have the same crazy results it's pretty much time to blame the tools. After all templates are supposed to be a good replacement for a [trivial code writer](https://github.com/rdebath/Brainfuck/blob/broken-and-trivial/trivial-bf2c.c) but when the difference is kilo bytes to giga bytes something ain't right.

BTW: I tried my [torture test](https://github.com/rdebath/Brainfuck/blob/master/bitwidth.b)  ... 60G then the OOM killer got it.

**Comment by SephDB** [comment]
On a version without comments, I get that the old version takes less memory(600MB vs 700MB). I unfortunately don't have a template profiler to see where the performance problems lie.

**Comment by SephDB** [comment]
It looks like gcc really hates working with value templates. I reworked it to work with type templates exclusively and now the whole thing compiles with 200MB in 5 seconds.

**Comment by rdebath** [comment]
You haven't pushed `type_tests.h` 

As for other programs you might try Urban Müller's primes program. It seemed to max out at about 30Gb of swap and was running happily in 4Gb or RAM when I got bored waiting for it to finish.

``` bf
+++++++++[->++++++++++++>+++++++++++++>++++>+++++++++++>++++++>+++++++++
<<<<<<]>>>>>>-.<<<<---.<---.++++.>>>++.<<+.>----.<++.<+++.>>.<-.<-.>>>>+
+++.<<.>>>[-]<[-]<[-]<[-]<[-]<[-]<[-]>[-]+[[-]>[-],[+[-----------[>[-]++
++++[<------>-]<--<<[->>++++++++++<<]>>[-<<+>>]<+>]]]<]+<-[>+>[-]>[-]<<[
>+>+<<-]>>[<<+>>-]+<-->>>>>>>>+<<<<<<<<[>+<-<[>>>+>+<<<<-]>>>>[<<<<+>>>>
-]<<[>>+>+<<<-]>>>[<<<+>>>-][-]>[-]<<[>+>+<<-]>>[<<+>>-]>>[-]<<<<<[>>>>>
[-]+<<[-]>[-]<<[>+>+<<-]>>[<<+>>-]<[>>[-]<<-]>>[<<<[-]>[-]<<[>+>+<<-]>>[
<<+>>-]>>[-]]<<<-<<-]+>>[<<[-]>>-]<[-]<[>>>>>>[-]<<<<<<-][-]>[-]<<<]>>>>
>>>>[-<<<<<<<[-]<<[>>+>+<<<-]>>>[<<<+>>>-]<[>+<-]>[[>+>+<<-]>>[<<+>>-]++
+++++++<[>>>+<<[>+>[-]<<-]>[<+>-]>[<<++++++++++>>-]<<-<-]+++++++++>[<->-
]<[>+<-]<[>+<-]<[>+<-]>>>[<<<+>>>-]+++++++++<[>>>+<<[>+>[-]<<-]>[<+>-]>[
<<++++++++++>>>+<-]<<-<-]>>>>[<<<<+>>>>-]<<<[-]<<+>]<[[>+<-]+++++++[<+++
++++>-]<-.[-]>>[<<+>>-]<<-]>++++[<++++++++>-]<.[-]>>>>>>>]<<<<<<<[-]<[-]
<<-]++++++++++.[-]
```

Or maybe just something to slowly print out the alphabet.
```bf
>++++++++[>+++>>>++++++++<<<<-]>++<<+[>>>[>>]<[[->>+<
<]>>>+.[->>+<<]<-[<<]]>+<<[-<<]<]>+>>[-<<]<+++++++++.
```

**Comment by SephDB** [comment]
I've pushed it now.
The prime program happily compiles with ~1GB of RAM usage in 1m22s on my Windows machine.
